// <auto-generated />
// This file is auto-generated from core/models/src/vault/FieldKey.ts
// Do not edit this file directly. Run 'npm run generate:models' to regenerate.

package net.aliasvault.app.vaultstore.models

/**
 * System field keys for the field-based data model.
 * These keys map to FieldDefinition.FieldKey values.
 */
object FieldKey {
    /**
     * Type: Text.
     */
    const val LOGIN_USERNAME = "login.username"

    /**
     * Type: Password.
     */
    const val LOGIN_PASSWORD = "login.password"

    /**
     * Type: Email.
     */
    const val LOGIN_EMAIL = "login.email"

    /**
     * Type: URL.
     */
    const val LOGIN_URL = "login.url"

    /**
     * Type: Text.
     */
    const val CARD_NUMBER = "card.number"

    /**
     * Type: Text.
     */
    const val CARD_CARDHOLDER_NAME = "card.cardholder_name"

    /**
     * Type: Text.
     */
    const val CARD_EXPIRY_MONTH = "card.expiry_month"

    /**
     * Type: Text.
     */
    const val CARD_EXPIRY_YEAR = "card.expiry_year"

    /**
     * Type: Password.
     */
    const val CARD_CVV = "card.cvv"

    /**
     * Type: Password.
     */
    const val CARD_PIN = "card.pin"

    /**
     * Type: Text.
     */
    const val ALIAS_FIRST_NAME = "alias.first_name"

    /**
     * Type: Text.
     */
    const val ALIAS_LAST_NAME = "alias.last_name"

    /**
     * Type: Text.
     */
    const val ALIAS_GENDER = "alias.gender"

    /**
     * Type: Date.
     */
    const val ALIAS_BIRTHDATE = "alias.birthdate"

    /**
     * Type: TextArea.
     */
    const val NOTES_CONTENT = "notes.content"
}
