// <auto-generated />
// This file is auto-generated from core/models/src/vault/Item.ts
// Do not edit this file directly. Run 'npm run generate:models' to regenerate.

package net.aliasvault.app.vaultstore.models

/**
 * Item types supported by the vault.
 */
object ItemType {
    /**
     * Login item type.
     */
    const val LOGIN = "Login"

    /**
     * Alias item type.
     */
    const val ALIAS = "Alias"

    /**
     * CreditCard item type.
     */
    const val CREDIT_CARD = "CreditCard"

    /**
     * Note item type.
     */
    const val NOTE = "Note"

    /**
     * All available item types.
     */
    val all = listOf(LOGIN, ALIAS, CREDIT_CARD, NOTE)

    /**
     * Checks if a string value is a valid item type.
     */
    fun isValid(value: String?): Boolean {
        return value in all
    }
}
