// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasServerDb.Migrations
{
    /// <inheritdoc />
    public partial class ConfigureMobileLoginRequestCascadeDelete : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_MobileLoginRequests_AliasVaultUsers_UserId",
                table: "MobileLoginRequests");

            migrationBuilder.AddForeignKey(
                name: "FK_MobileLoginRequests_AliasVaultUsers_UserId",
                table: "MobileLoginRequests",
                column: "UserId",
                principalTable: "AliasVaultUsers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_MobileLoginRequests_AliasVaultUsers_UserId",
                table: "MobileLoginRequests");

            migrationBuilder.AddForeignKey(
                name: "FK_MobileLoginRequests_AliasVaultUsers_UserId",
                table: "MobileLoginRequests",
                column: "UserId",
                principalTable: "AliasVaultUsers",
                principalColumn: "Id");
        }
    }
}
