// <auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasServerDb.Migrations
{
    /// <inheritdoc />
    public partial class AddUserEmailClaimCompositeIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_UserEmailClaims_UserId",
                table: "UserEmailClaims");

            migrationBuilder.CreateIndex(
                name: "IX_UserEmailClaims_UserId_Disabled",
                table: "UserEmailClaims",
                columns: new[] { "UserId", "Disabled" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_UserEmailClaims_UserId_Disabled",
                table: "UserEmailClaims");

            migrationBuilder.CreateIndex(
                name: "IX_UserEmailClaims_UserId",
                table: "UserEmailClaims",
                column: "UserId");
        }
    }
}
