name: Feature Request
description: Suggest a new feature or enhancement for AliasVault
title: "[Feature Request] "
labels: ["⚡️ enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature!

        We appreciate your ideas to improve AliasVault. Please provide as much detail as possible.

        **Before submitting:**
        - Search [existing feature requests](https://github.com/aliasvault/aliasvault/issues?q=is%3Aissue%20label%3A"⚡%EF%B8%8F%20enhancement"%20state%3Aopen) to avoid duplicates
        - Check the [v1.0 roadmap](https://github.com/aliasvault/aliasvault/issues/731)

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing feature requests and this is not a duplicate
          required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) should this feature be available on?
      multiple: true
      options:
        - All Platforms
        - Web App
        - Browser Extension (Chrome/Firefox/Edge/Safari)
        - Mobile App (iOS)
        - Mobile App (Android)
        - Server/API
        - Admin Portal
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Feature
        - Enhancement to Existing Feature
        - UI/UX Improvement
        - Performance Improvement
        - Security Enhancement
        - Integration/API
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        I'm always frustrated when...
        It would be helpful to have...
        Currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        I would like to have a feature that...
        This could work by...
        The user would be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I've tried...
        Another option could be...
        This is different from... because...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request, for example mockups, example screenshots, etc.
      placeholder: |
        This would help with...
        Similar to how [other app] does it...
        Could integrate with...
    validations:
      required: false
