name: Feature Request
description: Suggest a new feature or enhancement for AliasVault
title: "[Feature Request]: "
labels: ["⚡️ enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature!

        We appreciate your ideas to improve AliasVault. Please provide as much detail as possible.

        **Before submitting:**
        - Search [existing feature requests](https://github.com/yourusername/AliasVault/issues?q=is%3Aissue+label%3A%22⚡️+enhancement%22) to avoid duplicates
        - Check the [roadmap](https://github.com/yourusername/AliasVault/projects) if available

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing feature requests and this is not a duplicate
          required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) should this feature be available on?
      multiple: true
      options:
        - All Platforms
        - Web App
        - Browser Extension (Chrome/Firefox/Edge/Safari)
        - Mobile App (iOS)
        - Mobile App (Android)
        - Server/API
        - Admin Portal
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Feature
        - Enhancement to Existing Feature
        - UI/UX Improvement
        - Performance Improvement
        - Security Enhancement
        - Integration/API
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        I'm always frustrated when...
        It would be helpful to have...
        Currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        I would like to have a feature that...
        This could work by...
        The user would be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I've tried...
        Another option could be...
        This is different from... because...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: |
        If applicable, add mockups, wireframes, or examples from other apps.
        Drag and drop images here, or paste from clipboard.
      placeholder: |
        Drag and drop files here or paste screenshots...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request
      placeholder: |
        This would help with...
        Similar to how [other app] does it...
        Could integrate with...
    validations:
      required: false
