// <auto-generated />
// This file is auto-generated from shared/models/src/vault/FieldKey.ts
// Do not edit this file directly. Run 'npm run generate:models' to regenerate.

import Foundation

/// System field keys for the field-based data model.
/// These keys map to FieldDefinition.FieldKey values.
public struct FieldKey {
    /// Type: Text
    public static let loginUsername = "login.username"

    /// Type: Password
    public static let loginPassword = "login.password"

    /// Type: Text
    public static let loginNotes = "login.notes"

    /// Type: Email
    public static let loginEmail = "login.email"

    /// Type: URL
    public static let loginUrl = "login.url"

    /// Type: Text
    public static let loginRecoveryCodes = "login.recovery_codes"

    /// Type: Text
    public static let cardNumber = "card.number"

    /// Type: Text
    public static let cardCardholderName = "card.cardholder_name"

    /// Type: Text
    public static let cardExpiryMonth = "card.expiry_month"

    /// Type: Text
    public static let cardExpiryYear = "card.expiry_year"

    /// Type: Password
    public static let cardCvv = "card.cvv"

    /// Type: Password
    public static let cardPin = "card.pin"

    /// Type: Text
    public static let identityTitle = "identity.title"

    /// Type: Text
    public static let identityFirstName = "identity.first_name"

    /// Type: Text
    public static let identityMiddleName = "identity.middle_name"

    /// Type: Text
    public static let identityLastName = "identity.last_name"

    /// Type: Email
    public static let identityEmail = "identity.email"

    /// Type: Text
    public static let identityPhoneNumbers = "identity.phone_numbers"

    /// Type: Text
    public static let identityAddressLine1 = "identity.address_line1"

    /// Type: Text
    public static let identityAddressLine2 = "identity.address_line2"

    /// Type: Text
    public static let identityCity = "identity.city"

    /// Type: Text
    public static let identityState = "identity.state"

    /// Type: Text
    public static let identityPostalCode = "identity.postal_code"

    /// Type: Text
    public static let identityCountry = "identity.country"

    /// Type: Text
    public static let aliasFirstName = "alias.first_name"

    /// Type: Text
    public static let aliasLastName = "alias.last_name"

    /// Type: Text
    public static let aliasGender = "alias.gender"

    /// Type: Date
    public static let aliasBirthdate = "alias.birthdate"

    /// Type: TextArea
    public static let notesContent = "notes.content"
}
