// <auto-generated />
// This file is auto-generated from core/models/src/vault/Item.ts
// Do not edit this file directly. Run 'npm run generate:models' to regenerate.

import Foundation

/// Item types supported by the vault.
public struct ItemType {
    /// Login item type.
    public static let login = "Login"

    /// Alias item type.
    public static let alias = "Alias"

    /// CreditCard item type.
    public static let creditCard = "CreditCard"

    /// Note item type.
    public static let note = "Note"

    /// All available item types.
    public static let all = [login, alias, creditCard, note]

    /// Checks if a string value is a valid item type.
    public static func isValid(_ value: String?) -> Bool {
        guard let value = value else { return false }
        return all.contains(value)
    }
}
