//-----------------------------------------------------------------------
// <copyright file="SqlStatement.cs" company="aliasvault">
// Copyright (c) aliasvault. All rights reserved.
// Licensed under the AGPLv3 license. See LICENSE.md file in the project root for full license information.
// </copyright>
//-----------------------------------------------------------------------

namespace AliasVault.Client.Services.JsInterop.RustCore;

using System.Text.Json.Serialization;

/// <summary>
/// A SQL statement with its parameter values, generated by the merge operation.
/// </summary>
public class SqlStatement
{
    /// <summary>
    /// Gets or sets the SQL query with ? placeholders.
    /// </summary>
    [JsonPropertyName("sql")]
    public string Sql { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets parameter values in order.
    /// </summary>
    [JsonPropertyName("params")]
    public List<object?> Params { get; set; } = [];
}
