// <auto-generated />
// This file is auto-generated from shared/models/src/vault/FieldKey.ts
// Do not edit this file directly. Run 'npm run generate:models' to regenerate.

namespace AliasClientDb.Models;

/// <summary>
/// System field keys for the field-based data model.
/// These keys map to FieldDefinition.FieldKey values.
/// </summary>
public static class FieldKey
{
    /// <summary>
    /// Type: Text
    /// </summary>
    public const string LoginUsername = "login.username";

    /// <summary>
    /// Type: Password
    /// </summary>
    public const string LoginPassword = "login.password";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string LoginNotes = "login.notes";

    /// <summary>
    /// Type: Email
    /// </summary>
    public const string LoginEmail = "login.email";

    /// <summary>
    /// Type: URL
    /// </summary>
    public const string LoginUrl = "login.url";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string LoginRecoveryCodes = "login.recovery_codes";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string CardNumber = "card.number";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string CardCardholderName = "card.cardholder_name";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string CardExpiryMonth = "card.expiry_month";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string CardExpiryYear = "card.expiry_year";

    /// <summary>
    /// Type: Password
    /// </summary>
    public const string CardCvv = "card.cvv";

    /// <summary>
    /// Type: Password
    /// </summary>
    public const string CardPin = "card.pin";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string IdentityTitle = "identity.title";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string IdentityFirstName = "identity.first_name";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string IdentityMiddleName = "identity.middle_name";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string IdentityLastName = "identity.last_name";

    /// <summary>
    /// Type: Email
    /// </summary>
    public const string IdentityEmail = "identity.email";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string IdentityPhoneNumbers = "identity.phone_numbers";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string IdentityAddressLine1 = "identity.address_line1";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string IdentityAddressLine2 = "identity.address_line2";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string IdentityCity = "identity.city";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string IdentityState = "identity.state";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string IdentityPostalCode = "identity.postal_code";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string IdentityCountry = "identity.country";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string AliasFirstName = "alias.first_name";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string AliasLastName = "alias.last_name";

    /// <summary>
    /// Type: Text
    /// </summary>
    public const string AliasGender = "alias.gender";

    /// <summary>
    /// Type: Date
    /// </summary>
    public const string AliasBirthdate = "alias.birthdate";
}
