// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _180SystemFieldRefactor : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_FieldDefinitions_FieldKey",
                table: "FieldDefinitions");

            migrationBuilder.DropColumn(
                name: "FieldKey",
                table: "FieldDefinitions");

            migrationBuilder.AlterColumn<Guid>(
                name: "FieldDefinitionId",
                table: "FieldValues",
                type: "TEXT",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "TEXT");

            migrationBuilder.AddColumn<string>(
                name: "FieldKey",
                table: "FieldValues",
                type: "TEXT",
                maxLength: 100,
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_FieldValues_FieldKey",
                table: "FieldValues",
                column: "FieldKey");

            migrationBuilder.CreateIndex(
                name: "IX_FieldValues_ItemId_FieldKey",
                table: "FieldValues",
                columns: new[] { "ItemId", "FieldKey" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_FieldValues_FieldKey",
                table: "FieldValues");

            migrationBuilder.DropIndex(
                name: "IX_FieldValues_ItemId_FieldKey",
                table: "FieldValues");

            migrationBuilder.DropColumn(
                name: "FieldKey",
                table: "FieldValues");

            migrationBuilder.AlterColumn<Guid>(
                name: "FieldDefinitionId",
                table: "FieldValues",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "TEXT",
                oldNullable: true);

            migrationBuilder.AddColumn<string>(
                name: "FieldKey",
                table: "FieldDefinitions",
                type: "TEXT",
                maxLength: 100,
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_FieldDefinitions_FieldKey",
                table: "FieldDefinitions",
                column: "FieldKey");
        }
    }
}
