// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AliasClientDb.Migrations
{
    /// <inheritdoc />
    public partial class _171RenameColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "DefaultVisibility",
                table: "FieldDefinitions");

            migrationBuilder.DropColumn(
                name: "EntityType",
                table: "FieldDefinitions");

            migrationBuilder.RenameColumn(
                name: "DisplayOrder",
                table: "Folders",
                newName: "Weight");

            migrationBuilder.RenameColumn(
                name: "ValueIndex",
                table: "FieldValues",
                newName: "Weight");

            migrationBuilder.RenameIndex(
                name: "IX_FieldValues_ItemId_FieldDefinitionId_ValueIndex",
                table: "FieldValues",
                newName: "IX_FieldValues_ItemId_FieldDefinitionId_Weight");

            migrationBuilder.RenameColumn(
                name: "DisplayOrder",
                table: "FieldDefinitions",
                newName: "Weight");

            migrationBuilder.AddColumn<bool>(
                name: "IsHidden",
                table: "FieldDefinitions",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsHidden",
                table: "FieldDefinitions");

            migrationBuilder.RenameColumn(
                name: "Weight",
                table: "Folders",
                newName: "DisplayOrder");

            migrationBuilder.RenameColumn(
                name: "Weight",
                table: "FieldValues",
                newName: "ValueIndex");

            migrationBuilder.RenameIndex(
                name: "IX_FieldValues_ItemId_FieldDefinitionId_Weight",
                table: "FieldValues",
                newName: "IX_FieldValues_ItemId_FieldDefinitionId_ValueIndex");

            migrationBuilder.RenameColumn(
                name: "Weight",
                table: "FieldDefinitions",
                newName: "DisplayOrder");

            migrationBuilder.AddColumn<string>(
                name: "DefaultVisibility",
                table: "FieldDefinitions",
                type: "TEXT",
                maxLength: 50,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "EntityType",
                table: "FieldDefinitions",
                type: "TEXT",
                maxLength: 50,
                nullable: true);
        }
    }
}
